
services:
  app:
    build: .
    container_name: product_service
    ports:
      - "2000:2000"
    depends_on:
      - postgres_db


  postgres_db:
    image: postgres:latest
    container_name: postgres12
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/products_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Barbell@123
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Barbell@123
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
