---
# Spring Boot Application Deployment with 3 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 3  # Scaling to 3 replicas
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: saiteja413/productservice-app:latest
          ports:
            - containerPort: 2000  # Container listens on port 2000
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/products_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Barbell@123"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app  # Service name
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080  # Exposed on port 8080
      targetPort: 2000  # Forward traffic to container's port 2000
      nodePort: 30008  # Expose on nodePort 30008 for external access
  type: NodePort
